# Generated by Django 4.2.5 on 2023-09-11 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=75)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('technologies_used', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.TextField()),
                ('code_url', models.URLField(max_length=300)),
                ('deployment_url', models.URLField(max_length=300)),
                ('priority', models.DecimalField(decimal_places=2, max_digits=3)),
                ('slug', models.SlugField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='skill_icons')),
                ('skill_title', models.CharField(max_length=50)),
                ('skill_description', models.CharField(max_length=75)),
                ('priority', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images')),
                ('image_title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('caption', models.CharField(max_length=150)),
                ('priority', models.DecimalField(decimal_places=2, max_digits=3)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='website.project')),
            ],
        ),
    ]
