# Generated by Django 4.2.5 on 2023-09-11 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_image_image_title_alter_image_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='project_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_title',
            field=models.CharField(help_text='MAX_LENGTH = 150', max_length=150, verbose_name='Image Title'),
        ),
        migrations.AlterField(
            model_name='image',
            name='priority',
            field=models.IntegerField(help_text='Enter an Integer', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, help_text='Optional. MAX_LENGTH = 150', max_length=150, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_url',
            field=models.URLField(blank=True, help_text='MAX_LENGTH = 300', max_length=300, null=True, verbose_name='Code URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deployment_url',
            field=models.URLField(blank=True, help_text='MAX_LENGTH = 300', max_length=300, null=True, verbose_name='Deployment URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='long_description',
            field=models.TextField(verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(help_text='MAX_LENGTH = 75', max_length=75, verbose_name='Project Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(help_text='Try to reach 125 characters for uniform card sizes. MAX_LENGTH = 150', max_length=150, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Optional. MAX_LENGTH = 150', max_length=150, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='software_type',
            field=models.CharField(help_text='MAX_LENGTH = 50', max_length=50, verbose_name='Software Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies_used',
            field=models.CharField(help_text='MAX_LENGTH = 150', max_length=150, verbose_name='Technologies Used'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(upload_to='skill_icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='priority',
            field=models.IntegerField(help_text='Enter an Integer', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_description',
            field=models.CharField(help_text='MAX_LENGTH = 75', max_length=75, verbose_name='Skill Description'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_title',
            field=models.CharField(help_text='MAX_LENGTH = 50', max_length=50, verbose_name='Skill Title'),
        ),
    ]
