# Generated by Django 4.2.5 on 2023-09-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_skill_skill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=True, help_text='Is it a featured Project?', verbose_name='Featured Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=1, help_text='Enter an Integer', verbose_name='Priority'),
        ),
    ]
