# Generated by Django 4.2.5 on 2023-09-17 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_project_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='priority',
        ),
    ]
