# Generated by Django 4.2.5 on 2023-09-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_project_featured_remove_project_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=1, help_text='Enter an Integer', verbose_name='Priority'),
        ),
    ]
