# Generated by Django 4.2.5 on 2023-09-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_project_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lines_of_code',
            field=models.PositiveIntegerField(default=0, help_text='How many lines of code was this project?', verbose_name='Lines of Code'),
        ),
    ]
