# Generated by Django 4.2.5 on 2023-09-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_project_lines_of_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_title',
            field=models.CharField(help_text='MAX_LENGTH = 150. OPTIONAL', max_length=150, verbose_name='Image Title'),
        ),
    ]
