# Generated by Django 4.2.5 on 2023-09-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_image_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='priority',
            field=models.IntegerField(default=1, help_text='Enter an Integer', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='priority',
            field=models.IntegerField(default=1, help_text='Enter an Integer', verbose_name='Priority'),
        ),
    ]
