# Generated by Django 4.2.5 on 2024-02-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_project_message_project_show_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='skill_icons', verbose_name='Icon')),
                ('certification_title', models.CharField(help_text='MAX_LENGTH = 50', max_length=50, verbose_name='Certification Title')),
                ('issued_on', models.DateField(verbose_name='Issued on (date)')),
                ('expires_on', models.DateField(verbose_name='Expires on (date)')),
                ('priority', models.IntegerField(default=1, help_text='Enter an Integer', verbose_name='Priority')),
            ],
        ),
    ]
