# Generated by Django 4.2.5 on 2024-02-04 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_certifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certifications',
            new_name='Certification',
        ),
    ]
