# Generated by Django 4.2.5 on 2024-02-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_rename_certifications_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='badge_url',
            field=models.URLField(default='test', help_text='MAX_LENGTH = 300', max_length=300, verbose_name='Badge URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certification',
            name='icon',
            field=models.ImageField(help_text='Try to keep the image at 128x128', upload_to='skill_icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(help_text='Try to keep the image at 64x64', upload_to='skill_icons', verbose_name='Icon'),
        ),
    ]
