# Generated by Django 4.2.5 on 2024-02-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_certification_badge_url_alter_certification_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='link_name',
            field=models.CharField(default='test', help_text='The name of link where the badge can be verified (example: Credly). MAX_LENGTH = 50', max_length=50, verbose_name='Link Name'),
            preserve_default=False,
        ),
    ]
